### ISSUE TITLE
error when trying to open a cheat-sheet throught the search engin and not logged in

### ISSUE THREAD

**Issue by gand-elf13** [leonardo-racic/fish-a-fiche#6]
File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/Documents/GitHub/fish-a-fiche/app.py", line 91, in cheat_sheet
    return handle_cheat_sheet(cheat_sheet_manager, server_account_manager, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/Documents/GitHub/fish-a-fiche/modules/handle_cheat_sheet.py", line 34, in handle_cheat_sheet
    user_collections: list = server_account_manager.get_user_account_collections()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/Documents/GitHub/fish-a-fiche/modules/server_account_manager.py", line 319, in get_user_account_collections
    return self.get_collections(self.get_user_account_token())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/Documents/GitHub/fish-a-fiche/modules/server_account_manager.py", line 315, in get_collections
    return json_data["accounts"][token].get("collections")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: ''
Traceback (most recent call last):
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.local/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/Documents/GitHub/fish-a-fiche/app.py", line 91, in cheat_sheet
    return handle_cheat_sheet(cheat_sheet_manager, server_account_manager, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/Documents/GitHub/fish-a-fiche/modules/handle_cheat_sheet.py", line 34, in handle_cheat_sheet
    user_collections: list = server_account_manager.get_user_account_collections()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/Documents/GitHub/fish-a-fiche/modules/server_account_manager.py", line 319, in get_user_account_collections
    return self.get_collections(self.get_user_account_token())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/Documents/GitHub/fish-a-fiche/modules/server_account_manager.py", line 315, in get_collections
    return json_data["accounts"][token].get("collections")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: ''

**Comment by gand-elf13** [comment]
throught testing it appear that it is linked to cookies : same page bug when opened without cookies but rendered correctly if opened with a login cookie

**Comment by gand-elf13** [comment]
this error is unrelated to the search engine, it also happen when just opening a cheat sheet page without cookies

**Comment by gand-elf13** [comment]
it apear to be wotking fine if user logged in but not as the author of cheat sheet

**Comment by gand-elf13** [comment]
this also affect profiles when not logged in

**Comment by gand-elf13** [comment]
errors is generated by line 175 of  server account manager.py ,
    def get_user_account_info(self) -> dict:
        self.update()
        user_account: Account = self.get_user_account()
        if user_account is None:
            return {}
        return user_account.get_info()
 which return an empty dict if not logged in, 

but handle profile and handle cs expect this dictionnary to contain keys which are non existant.

**Comment by gand-elf13** [comment]
changed the empty dictionnary to be an empty but with accout structure :

            return {'username': '',
                    'password': '',
                    'description': '',
                    'profile_picture': '',
                    'id': '',
                    'cheat_sheet': [],
                    'collections': []}

corrected bug but may generate more : to surveil

**Comment by gand-elf13** [comment]
both errores where correcte with latest commit
